allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  argon2: true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  prisma: true
  unrs-resolver: true
